# Generated by Django 3.2.4 on 2021-06-26 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_statement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='user',
        ),
        migrations.AddField(
            model_name='statement',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
