# Generated by Django 3.2.4 on 2021-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210626_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='user',
        ),
        migrations.AddField(
            model_name='statement',
            name='fnam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
