# Generated by Django 3.2.4 on 2021-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210626_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='debit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='billno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
