# Generated by Django 3.2.4 on 2021-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210627_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
