# Generated by Django 3.2.4 on 2021-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_state_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='debit',
            field=models.IntegerField(default=0),
        ),
    ]
